-- Blixibon

-- Used by the Enhanced Sandbox NPCs addon

ESBOXNPCS_MapHeliNodes = {
	-- Spawn Field
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn1", Origin = "0 -640 -10560", Target = "esboxnpcs_helitrack_spawn2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn2", Origin = "1088 -3328 -10560", Target = "esboxnpcs_helitrack_spawn3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn3", Origin = "-896 -3712 -10560", Target = "esboxnpcs_helitrack_spawn4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn4", Origin = "-1024 -1024 -10560", Target = "esboxnpcs_helitrack_spawn5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn5", Origin = "-2560 -896 -10560", Target = "esboxnpcs_helitrack_spawn6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn6", Origin = "-2688 768 -10560", Target = "esboxnpcs_helitrack_spawn7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_spawn7", Origin = "192 1024 -10560", Target = "esboxnpcs_helitrack_spawn1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Twin Towers
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower1", Origin = "-896 -6144 1024", Target = "esboxnpcs_helitrack_tower2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower2", Origin = "384 -6144 1024", Target = "esboxnpcs_helitrack_tower3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower3", Origin = "384 -8384 1024", Target = "esboxnpcs_helitrack_tower4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower4", Origin = "384 -11008 1024", Target = "esboxnpcs_helitrack_tower5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower5", Origin = "3520 -11008 1024", Target = "esboxnpcs_helitrack_tower6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower6", Origin = "3520 -8384 1024", Target = "esboxnpcs_helitrack_tower7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower7", Origin = "-1920 -8384 1024", Target = "esboxnpcs_helitrack_tower8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_tower8", Origin = "-1856 -6144 1024", Target = "esboxnpcs_helitrack_tower1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Hotel
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_hotel1", Origin = "-192 1664 -8960", Target = "esboxnpcs_helitrack_hotel2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_hotel2", Origin = "640 2048 -8960", Target = "esboxnpcs_helitrack_hotel3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_hotel3", Origin = "512 3456 -8960", Target = "esboxnpcs_helitrack_hotel4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_hotel4", Origin = "-896 3456 -8960", Target = "esboxnpcs_helitrack_hotel5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_hotel5", Origin = "-1024 2048 -8960", Target = "esboxnpcs_helitrack_hotel1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Highway
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway1", Origin = "-6016 -448 -10368", Target = "esboxnpcs_helitrack_highway2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway2", Origin = "-6016 2560 -9984", Target = "esboxnpcs_helitrack_highway3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway3", Origin = "-5120 3584 -9984", Target = "esboxnpcs_helitrack_highway4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway4", Origin = "-3584 3584 -9984", Target = "esboxnpcs_helitrack_highway5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway5", Origin = "-2048 3520 -9984", Target = "esboxnpcs_helitrack_highway6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway6", Origin = "-512 3520 -9984", Target = "esboxnpcs_helitrack_highway7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway7", Origin = "1344 3584 -9984", Target = "esboxnpcs_helitrack_highway8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway8", Origin = "3072 3584 -9984", Target = "esboxnpcs_helitrack_highway9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway9", Origin = "4288 3584 -9984", Target = "esboxnpcs_helitrack_highway10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway10", Origin = "5632 3584 -9984", Target = "esboxnpcs_helitrack_highway11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway11", Origin = "7168 3648 -9984", Target = "esboxnpcs_helitrack_highway12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway12", Origin = "7904 3648 -9984", Target = "esboxnpcs_helitrack_highway13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway13", Origin = "9216 3648 -9984", Target = "esboxnpcs_helitrack_highway14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway14", Origin = "11264 3648 -9984", Target = "esboxnpcs_helitrack_highway15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway15", Origin = "12032 3904 -9984", Target = "esboxnpcs_helitrack_highway16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway16", Origin = "12416 4608 -9984", Target = "esboxnpcs_helitrack_highway17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway17", Origin = "12416 6464 -9984", Target = "esboxnpcs_helitrack_highway18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway18", Origin = "11520 7296 -9984", Target = "esboxnpcs_helitrack_highway19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway19", Origin = "10368 7296 -9984", Target = "esboxnpcs_helitrack_highway20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway20", Origin = "7616 7296 -10432", Target = "esboxnpcs_helitrack_highway21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway21", Origin = "6144 7296 -10560", Target = "esboxnpcs_helitrack_highway22", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway22", Origin = "5120 7296 -10560", Target = "esboxnpcs_helitrack_highway23", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway23", Origin = "5056 6144 -10560", Target = "esboxnpcs_helitrack_highway24", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway24", Origin = "6144 6144 -10560", Target = "esboxnpcs_helitrack_highway25", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway25", Origin = "7680 6144 -10560", Target = "esboxnpcs_helitrack_highway26", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway26", Origin = "8704 6144 -10560", Target = "esboxnpcs_helitrack_highway27", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway27", Origin = "9984 6144 -10560", Target = "esboxnpcs_helitrack_highway28", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway28", Origin = "10048 5120 -10560", Target = "esboxnpcs_helitrack_highway29", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway29", Origin = "10048 4608 -9664", Target = "esboxnpcs_helitrack_highway30", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway30", Origin = "10048 2560 -9664", Target = "esboxnpcs_helitrack_highway31", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway31", Origin = "10048 1024 -10560", Target = "esboxnpcs_helitrack_highway32", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway32", Origin = "11008 64 -10560", Target = "esboxnpcs_helitrack_highway33", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway33", Origin = "11008 -2560 -10560", Target = "esboxnpcs_helitrack_highway34", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway34", Origin = "11136 -4288 -10560", Target = "esboxnpcs_helitrack_highway35", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway35", Origin = "11136 -5824 -10560", Target = "esboxnpcs_helitrack_highway36", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway36", Origin = "10880 -10816 -10560", Target = "esboxnpcs_helitrack_highway37", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway37", Origin = "9216 -10944 -10560", Target = "esboxnpcs_helitrack_highway38", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_highway38", Origin = "8960 -11904 -10560", Target = "esboxnpcs_helitrack_canal1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Canal
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal1", Origin = "7808 -12288 -10880", Target = "esboxnpcs_helitrack_canal2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal2", Origin = "7808 -10880 -10624", Target = "esboxnpcs_helitrack_canal3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal3", Origin = "7808 -9088 -10624", Target = "esboxnpcs_helitrack_canal4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal4", Origin = "7808 -7680 -10880", Target = "esboxnpcs_helitrack_canal5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal5", Origin = "7808 -5120 -10880", Target = "esboxnpcs_helitrack_canal6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal6", Origin = "7808 -3584 -10880", Target = "esboxnpcs_helitrack_canal7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal7", Origin = "7808 -2112 -10624", Target = "esboxnpcs_helitrack_canal8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal8", Origin = "7808 -512 -10880", Target = "esboxnpcs_helitrack_canal9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal9", Origin = "7808 1024 -10880", Target = "esboxnpcs_helitrack_canal10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal10", Origin = "7808 3648 -9728", Target = "esboxnpcs_helitrack_canal11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal11", Origin = "7808 5120 -10496", Target = "esboxnpcs_helitrack_canal12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal12", Origin = "6336 4864 -10688", Target = "esboxnpcs_helitrack_canal13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal13", Origin = "4736 4864 -10432", Target = "esboxnpcs_helitrack_canal14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal14", Origin = "3328 4864 -10688", Target = "esboxnpcs_helitrack_canal15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal15", Origin = "3456 8192 -10688", Target = "esboxnpcs_helitrack_canal16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal16", Origin = "3328 11776 -10688", Target = "esboxnpcs_helitrack_canal17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal17", Origin = "2560 12544 -10688", Target = "esboxnpcs_helitrack_canal18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal18", Origin = "1024 12544 -10688", Target = "esboxnpcs_helitrack_canal19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal19", Origin = "-1024 12544 -10688", Target = "esboxnpcs_helitrack_canal20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal20", Origin = "-8704 12480 -10688", Target = "esboxnpcs_helitrack_canal21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal21", Origin = "-8768 12032 -10688", Target = "esboxnpcs_helitrack_canal22", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal22", Origin = "-8768 10368 -10240", Target = "esboxnpcs_helitrack_canal23", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal23", Origin = "-8768 6208 -10240", Target = "esboxnpcs_helitrack_canal24", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal24", Origin = "-4800 6144 -10240", Target = "esboxnpcs_helitrack_canal25", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal25", Origin = "-4800 5120 -10240", Target = "esboxnpcs_helitrack_canal26", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal26", Origin = "-4800 3584 -9664", Target = "esboxnpcs_helitrack_canal27", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal27", Origin = "-6144 3072 -9664", Target = "esboxnpcs_helitrack_canal28", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal28", Origin = "-8704 2752 -10496", Target = "esboxnpcs_helitrack_canal29", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal29", Origin = "-10816 2688 -10560", Target = "esboxnpcs_helitrack_canal30", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal30", Origin = "-10880 -512 -10560", Target = "esboxnpcs_helitrack_canal31", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_canal31", Origin = "-7680 -512 -10560", Target = "esboxnpcs_helitrack_highway1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Gooplex
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex1", Origin = "7680 10240 -10560", Target = "esboxnpcs_helitrack_gooplex2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex2", Origin = "8192 11264 -10560", Target = "esboxnpcs_helitrack_gooplex3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex3", Origin = "9216 11776 -10560", Target = "esboxnpcs_helitrack_gooplex4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex4", Origin = "10240 11264 -10560", Target = "esboxnpcs_helitrack_gooplex5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex5", Origin = "10752 10240 -10560", Target = "esboxnpcs_helitrack_gooplex6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex6", Origin = "10240 9216 -10560", Target = "esboxnpcs_helitrack_gooplex7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex7", Origin = "9216 8704 -10560", Target = "esboxnpcs_helitrack_gooplex8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_gooplex8", Origin = "8192 9216 -10560", Target = "esboxnpcs_helitrack_gooplex1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Lot
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot1", Origin = "-8192 1024 -10560", Target = "esboxnpcs_helitrack_lot2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot2", Origin = "-8448 0 -10560", Target = "esboxnpcs_helitrack_lot3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot3", Origin = "-9216 0 -10560", Target = "esboxnpcs_helitrack_lot4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot4", Origin = "-9984 0 -10560", Target = "esboxnpcs_helitrack_lot5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot5", Origin = "-10240 1024 -10560", Target = "esboxnpcs_helitrack_lot6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot6", Origin = "-9984 2048 -10560", Target = "esboxnpcs_helitrack_lot7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lot7", Origin = "-8448 2048 -10560", Target = "esboxnpcs_helitrack_lot1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Tower Street
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet1", Origin = "-10880 -5952 -10240", Target = "esboxnpcs_helitrack_towerstreet2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet2", Origin = "-7808 -5952 -10240", Target = "esboxnpcs_helitrack_towerstreet3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet3", Origin = "-5632 -5952 -10240", Target = "esboxnpcs_helitrack_towerstreet4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet4", Origin = "-4096 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet5", Origin = "-1408 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet6", Origin = "-320 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet7", Origin = "512 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet8", Origin = "3392 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet9", Origin = "6208 -5952 -10496", Target = "esboxnpcs_helitrack_towerstreet10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet10", Origin = "6208 -9088 -10496", Target = "esboxnpcs_helitrack_towerstreet11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet11", Origin = "3392 -9088 -10496", Target = "esboxnpcs_helitrack_towerstreet12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet12", Origin = "3392 -10880 -10496", Target = "esboxnpcs_helitrack_towerstreet13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet13", Origin = "704 -10880 -10496", Target = "esboxnpcs_helitrack_towerstreet14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet14", Origin = "512 -8576 -10496", Target = "esboxnpcs_helitrack_towerstreet15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet15", Origin = "-2176 -8576 -10496", Target = "esboxnpcs_helitrack_towerstreet16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet16", Origin = "-2176 -10880 -10496", Target = "esboxnpcs_helitrack_towerstreet17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet17", Origin = "-4096 -10880 -10496", Target = "esboxnpcs_helitrack_towerstreet18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet18", Origin = "-4096 -8640 -10496", Target = "esboxnpcs_helitrack_towerstreet19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet19", Origin = "-6528 -8640 -10496", Target = "esboxnpcs_helitrack_towerstreet20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet20", Origin = "-10880 -8640 -10496", Target = "esboxnpcs_helitrack_towerstreet21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_towerstreet21", Origin = "-10880 -6528 -10240", Target = "esboxnpcs_helitrack_towerstreet1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "lua_run", Targetname = "esboxnpcs_helitrack_autofly", Origin = "0 0 1024", Code = "ESBOXNPCS_InternalPathHandler(ACTIVATOR, CALLER)" },
}

