-- Blixibon

-- Used by the Enhanced Sandbox NPCs addon

ESBOXNPCS_MapHeliNodes = {
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main1", Origin = "3072 3072 640", Target = "esboxnpcs_helitrack_main2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main2", Origin = "2560 0 640", Target = "esboxnpcs_helitrack_main3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main3", Origin = "3072 -1024 640", Target = "esboxnpcs_helitrack_main4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main4", Origin = "4608 -1280 640", Target = "esboxnpcs_helitrack_main5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main5", Origin = "6144 -1344 640", Target = "esboxnpcs_helitrack_main6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main6", Origin = "8704 -960 640", Target = "esboxnpcs_helitrack_main7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main7", Origin = "9216 0 640", Target = "esboxnpcs_helitrack_main8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main8", Origin = "8704 512 640", Target = "esboxnpcs_helitrack_main9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main9", Origin = "6656 512 640", Target = "esboxnpcs_helitrack_main10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main10", Origin = "5376 1536 640", Target = "esboxnpcs_helitrack_main11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main11", Origin = "5312 3072 640", Target = "esboxnpcs_helitrack_main12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main12", Origin = "4800 3776 640", Target = "esboxnpcs_helitrack_main13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_main13", Origin = "3712 3776 640", Target = "esboxnpcs_helitrack_main1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex1", Origin = "1024 1024 704", Target = "esboxnpcs_helitrack_maincomplex2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex2", Origin = "1024 -1024 704", Target = "esboxnpcs_helitrack_maincomplex3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex3", Origin = "-512 -1024 1024", Target = "esboxnpcs_helitrack_maincomplex4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex4", Origin = "-2144 -1024 1024", Target = "esboxnpcs_helitrack_maincomplex5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex5", Origin = "-4096 -1024 1024", Target = "esboxnpcs_helitrack_maincomplex6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex6", Origin = "-4096 1280 1024", Target = "esboxnpcs_helitrack_maincomplex7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex7", Origin = "-4096 2816 1024", Target = "esboxnpcs_helitrack_maincomplex8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex8", Origin = "-2144 2816 1024", Target = "esboxnpcs_helitrack_maincomplex9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex9", Origin = "-1376 2464 1280", Target = "esboxnpcs_helitrack_maincomplex10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex10", Origin = "-384 2560 1280", Target = "esboxnpcs_helitrack_maincomplex11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_maincomplex11", Origin = "384 1920 896", Target = "esboxnpcs_helitrack_maincomplex1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water1", Origin = "-2560 -6656 640", Target = "esboxnpcs_helitrack_water2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water2", Origin = "-2144 -5632 768", Target = "esboxnpcs_helitrack_water3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water3", Origin = "-1280 -5504 768", Target = "esboxnpcs_helitrack_water4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water4", Origin = "256 -5888 512", Target = "esboxnpcs_helitrack_water5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water5", Origin = "2048 -6144 512", Target = "esboxnpcs_helitrack_water6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water6", Origin = "3072 -6400 512", Target = "esboxnpcs_helitrack_water7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water7", Origin = "4096 -6144 512", Target = "esboxnpcs_helitrack_water8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water8", Origin = "6144 -5888 512", Target = "esboxnpcs_helitrack_water9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water9", Origin = "9216 -6400 512", Target = "esboxnpcs_helitrack_water10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water10", Origin = "10240 -7168 512", Target = "esboxnpcs_helitrack_water11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water11", Origin = "12288 -8192 640", Target = "esboxnpcs_helitrack_water12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water12", Origin = "12800 -9216 768", Target = "esboxnpcs_helitrack_water13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water13", Origin = "12800 -10496 768", Target = "esboxnpcs_helitrack_water14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water14", Origin = "11776 -11264 768", Target = "esboxnpcs_helitrack_water15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water15", Origin = "9216 -11264 768", Target = "esboxnpcs_helitrack_water16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water16", Origin = "7168 -10752 768", Target = "esboxnpcs_helitrack_water17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water17", Origin = "4096 -10240 512", Target = "esboxnpcs_helitrack_water18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water18", Origin = "1024 -10496 512", Target = "esboxnpcs_helitrack_water19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water19", Origin = "0 -10752 384", Target = "esboxnpcs_helitrack_water20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water20", Origin = "-1024 -10752 384", Target = "esboxnpcs_helitrack_water21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water21", Origin = "-2048 -10752 384", Target = "esboxnpcs_helitrack_water22", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water22", Origin = "-1536 -8704 512", Target = "esboxnpcs_helitrack_water23", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_water23", Origin = "-2048 -7680 512", Target = "esboxnpcs_helitrack_water1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field1", Origin = "-5056 10240 1024", Target = "esboxnpcs_helitrack_field2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field2", Origin = "-4864 8448 1024", Target = "esboxnpcs_helitrack_field3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field3", Origin = "-4096 7424 1024", Target = "esboxnpcs_helitrack_field4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field4", Origin = "-2048 7424 1024", Target = "esboxnpcs_helitrack_field5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field5", Origin = "-256 7424 896", Target = "esboxnpcs_helitrack_field6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field6", Origin = "2560 7424 736", Target = "esboxnpcs_helitrack_field7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field7", Origin = "3072 8704 736", Target = "esboxnpcs_helitrack_field8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field8", Origin = "2944 10240 736", Target = "esboxnpcs_helitrack_field9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field9", Origin = "2048 10496 736", Target = "esboxnpcs_helitrack_field10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field10", Origin = "0 10496 896", Target = "esboxnpcs_helitrack_field11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field11", Origin = "-2048 11008 1024", Target = "esboxnpcs_helitrack_field12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field12", Origin = "-3584 10880 1024", Target = "esboxnpcs_helitrack_field13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_field13", Origin = "-4352 11136 1024", Target = "esboxnpcs_helitrack_field1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert1", Origin = "-14592 11008 1024", Target = "esboxnpcs_helitrack_desert2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert2", Origin = "-13312 10848 1024", Target = "esboxnpcs_helitrack_desert3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert3", Origin = "-12288 11264 1024", Target = "esboxnpcs_helitrack_desert4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert4", Origin = "-10240 10752 1024", Target = "esboxnpcs_helitrack_desert5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert5", Origin = "-10752 9216 1024", Target = "esboxnpcs_helitrack_desert6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert6", Origin = "-10240 8192 1024", Target = "esboxnpcs_helitrack_desert7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert7", Origin = "-9728 6144 1024", Target = "esboxnpcs_helitrack_desert8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert8", Origin = "-9728 4096 1152", Target = "esboxnpcs_helitrack_desert9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert9", Origin = "-9984 2048 1152", Target = "esboxnpcs_helitrack_desert10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert10", Origin = "-9856 512 1024", Target = "esboxnpcs_helitrack_desert11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert11", Origin = "-10112 -512 896", Target = "esboxnpcs_helitrack_desert12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert12", Origin = "-10752 -1024 768", Target = "esboxnpcs_helitrack_desert13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert13", Origin = "-11264 -2560 768", Target = "esboxnpcs_helitrack_desert14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert14", Origin = "-12288 -2816 768", Target = "esboxnpcs_helitrack_desert15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert15", Origin = "-13312 -2560 896", Target = "esboxnpcs_helitrack_desert16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert16", Origin = "-13568 -768 896", Target = "esboxnpcs_helitrack_desert17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert17", Origin = "-14080 512 1152", Target = "esboxnpcs_helitrack_desert18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert18", Origin = "-14336 2048 1536", Target = "esboxnpcs_helitrack_desert19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert19", Origin = "-14336 6144 1536", Target = "esboxnpcs_helitrack_desert20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert20", Origin = "-14336 8192 1280", Target = "esboxnpcs_helitrack_desert21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_desert21", Origin = "-14080 9472 1024", Target = "esboxnpcs_helitrack_desert1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "lua_run", Targetname = "esboxnpcs_helitrack_autofly", Origin = "0 0 1024", Code = "ESBOXNPCS_InternalPathHandler(ACTIVATOR, CALLER)" },
}

