-- Blixibon

-- Used by the Enhanced Sandbox NPCs addon

ESBOXNPCS_MapHeliNodes = {

	-- Town 1
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_1", Origin = "-11200 4800 -9408", Target = "esboxnpcs_helitrack_town1_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_2", Origin = "-11584 6144 -9408", Target = "esboxnpcs_helitrack_town1_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_3", Origin = "-14080 8576 -9408", Target = "esboxnpcs_helitrack_town1_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_4", Origin = "-13248 9536 -9408", Target = "esboxnpcs_helitrack_town1_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_5", Origin = "-11904 8192 -9408", Target = "esboxnpcs_helitrack_town1_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_6", Origin = "-11136 7936 -9408", Target = "esboxnpcs_helitrack_town1_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_7", Origin = "-8512 9216 -9408", Target = "esboxnpcs_helitrack_town1_8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_8", Origin = "-7360 8192 -9408", Target = "esboxnpcs_helitrack_town1_9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_9", Origin = "-6592 7360 -9408", Target = "esboxnpcs_helitrack_town1_10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_10", Origin = "-6656 6528 -9408", Target = "esboxnpcs_helitrack_town1_11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_11", Origin = "-7104 6080 -9408", Target = "esboxnpcs_helitrack_town1_12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_12", Origin = "-8320 5888 -9408", Target = "esboxnpcs_helitrack_town1_13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town1_13", Origin = "-9472 4800 -9408", Target = "esboxnpcs_helitrack_town1_1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Town 2
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_1", Origin = "-10240 11584 -9408", Target = "esboxnpcs_helitrack_town2_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_2", Origin = "-10240 14400 -9408", Target = "esboxnpcs_helitrack_town2_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_3", Origin = "-12160 14336 -9408", Target = "esboxnpcs_helitrack_town2_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_4", Origin = "-14208 14336 -9408", Target = "esboxnpcs_helitrack_town2_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_5", Origin = "-14144 12800 -9408", Target = "esboxnpcs_helitrack_town2_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_6", Origin = "-14144 11264 -9408", Target = "esboxnpcs_helitrack_town2_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_7", Origin = "-13184 11200 -9408", Target = "esboxnpcs_helitrack_town2_8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_town2_8", Origin = "-11264 11264 -9408", Target = "esboxnpcs_helitrack_town2_1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Docks
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_docks1", Origin = "-5120 13440 -9728", Target = "esboxnpcs_helitrack_docks2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_docks2", Origin = "-6144 12544 -9728", Target = "esboxnpcs_helitrack_docks3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_docks3", Origin = "-8192 12800 -9728", Target = "esboxnpcs_helitrack_docks4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_docks4", Origin = "-8832 13632 -9728", Target = "esboxnpcs_helitrack_docks5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_docks5", Origin = "-7168 14080 -9728", Target = "esboxnpcs_helitrack_docks1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Lighthouse
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse1", Origin = "-5120 7680 -8448", Target = "esboxnpcs_helitrack_lighthouse2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse2", Origin = "-3584 7168 -8448", Target = "esboxnpcs_helitrack_lighthouse3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse3", Origin = "-2048 8704 -8448", Target = "esboxnpcs_helitrack_lighthouse4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse4", Origin = "-2560 10240 -8448", Target = "esboxnpcs_helitrack_lighthouse5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse5", Origin = "-4352 10752 -8448", Target = "esboxnpcs_helitrack_lighthouse6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_lighthouse6", Origin = "-5632 8704 -8448", Target = "esboxnpcs_helitrack_lighthouse1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },

	-- Road 1
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_1", Origin = "-10240 1856 -9728", Target = "esboxnpcs_helitrack_road1_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_2", Origin = "-8704 1856 -9728", Target = "esboxnpcs_helitrack_road1_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_3", Origin = "-7168 1856 -9728", Target = "esboxnpcs_helitrack_road1_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_4", Origin = "-4864 2048 -9728", Target = "esboxnpcs_helitrack_road1_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_5", Origin = "-4224 1536 -9728", Target = "esboxnpcs_helitrack_road1_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_6", Origin = "-3968 512 -9728", Target = "esboxnpcs_helitrack_road1_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_7", Origin = "-4288 -1536 -9664", Target = "esboxnpcs_helitrack_road1_8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_8", Origin = "-4800 -2560 -9600", Target = "esboxnpcs_helitrack_road1_9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_9", Origin = "-4736 -4608 -9344", Target = "esboxnpcs_helitrack_road1_10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_10", Origin = "-4160 -4800 -9344", Target = "esboxnpcs_helitrack_road1_11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_11", Origin = "-3648 -4480 -9280", Target = "esboxnpcs_helitrack_road1_12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_12", Origin = "-3648 -3392 -9216", Target = "esboxnpcs_helitrack_road1_13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_13", Origin = "-3904 -2304 -9088", Target = "esboxnpcs_helitrack_road1_14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_14", Origin = "-3200 0 -9024", Target = "esboxnpcs_helitrack_road1_15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_15", Origin = "-2624 320 -8960", Target = "esboxnpcs_helitrack_road1_16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_16", Origin = "-1920 -512 -8832", Target = "esboxnpcs_helitrack_road1_17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_17", Origin = "-2240 -1664 -8704", Target = "esboxnpcs_helitrack_road1_18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_18", Origin = "-2752 -3072 -8640", Target = "esboxnpcs_helitrack_road1_19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_19", Origin = "-3328 -4992 -8640", Target = "esboxnpcs_helitrack_road1_20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_20", Origin = "-4608 -5632 -8640", Target = "esboxnpcs_helitrack_road1_21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_21", Origin = "-5760 -5760 -8576", Target = "esboxnpcs_helitrack_road1_22", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_22", Origin = "-6144 -7168 -8640", Target = "esboxnpcs_helitrack_road1_23", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_23", Origin = "-6784 -7808 -8640", Target = "esboxnpcs_helitrack_road1_24", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_24", Origin = "-7296 -8704 -8640", Target = "esboxnpcs_helitrack_road1_25", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_25", Origin = "-7296 -9728 -8640", Target = "esboxnpcs_helitrack_road1_26", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_26", Origin = "-6400 -10432 -8640", Target = "esboxnpcs_helitrack_road1_27", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_27", Origin = "-6144 -11776 -8640", Target = "esboxnpcs_helitrack_road1_28", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_28", Origin = "-6144 -13312 -8640", Target = "esboxnpcs_helitrack_road1_29", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_29", Origin = "-7168 -14336 -8640", Target = "esboxnpcs_helitrack_road1_30", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_30", Origin = "-9344 -13824 -8832", Target = "esboxnpcs_helitrack_road1_31", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_31", Origin = "-10752 -14528 -8896", Target = "esboxnpcs_helitrack_road1_32", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_32", Origin = "-11712 -14848 -8960", Target = "esboxnpcs_helitrack_road1_33", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_33", Origin = "-13824 -14848 -8960", Target = "esboxnpcs_helitrack_road1_34", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_34", Origin = "-14848 -14080 -8960", Target = "esboxnpcs_helitrack_road1_35", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_35", Origin = "-14848 -9728 -9216", Target = "esboxnpcs_helitrack_road1_36", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_36", Origin = "-14336 -8960 -9344", Target = "esboxnpcs_helitrack_road1_37", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_37", Origin = "-12416 -8960 -9344", Target = "esboxnpcs_helitrack_road1_38", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_38", Origin = "-11264 -8704 -9344", Target = "esboxnpcs_helitrack_road1_39", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_39", Origin = "-10944 -8192 -9408", Target = "esboxnpcs_helitrack_road1_40", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_40", Origin = "-10944 -6784 -9408", Target = "esboxnpcs_helitrack_road1_41", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_41", Origin = "-11904 -4992 -9600", Target = "esboxnpcs_helitrack_road1_42", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_42", Origin = "-11968 -2048 -9600", Target = "esboxnpcs_helitrack_road1_43", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_43", Origin = "-13376 -384 -9600", Target = "esboxnpcs_helitrack_road1_44", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_44", Origin = "-13312 1536 -9600", Target = "esboxnpcs_helitrack_road1_45", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road1_45", Origin = "-12288 1856 -9600", Target = "esboxnpcs_helitrack_road1_1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Road 2
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_1", Origin = "-4608 4032 -9728", Target = "esboxnpcs_helitrack_road2_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_2", Origin = "-4928 4864 -9728", Target = "esboxnpcs_helitrack_road2_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_3", Origin = "-4928 5440 -9728", Target = "esboxnpcs_helitrack_road2_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_4", Origin = "-4352 6016 -9728", Target = "esboxnpcs_helitrack_road2_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_5", Origin = "-2624 6016 -9600", Target = "esboxnpcs_helitrack_road2_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_6", Origin = "-1280 5248 -9536", Target = "esboxnpcs_helitrack_road2_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_7", Origin = "1216 5248 -9536", Target = "esboxnpcs_helitrack_road2_8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_8", Origin = "3072 6912 -9216", Target = "esboxnpcs_helitrack_road2_9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_9", Origin = "3840 7424 -8704", Target = "esboxnpcs_helitrack_road2_10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_10", Origin = "4928 7168 -8192", Target = "esboxnpcs_helitrack_road2_11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_11", Origin = "6144 6848 -8896", Target = "esboxnpcs_helitrack_road2_12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_12", Origin = "6528 6656 -9408", Target = "esboxnpcs_helitrack_road2_13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_13", Origin = "6912 5120 -9408", Target = "esboxnpcs_helitrack_road2_14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_14", Origin = "8704 5376 -9472", Target = "esboxnpcs_helitrack_road2_15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_15", Origin = "9728 5952 -9664", Target = "esboxnpcs_helitrack_road2_16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_16", Origin = "11264 7680 -9536", Target = "esboxnpcs_helitrack_road2_17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_17", Origin = "11264 9728 -9280", Target = "esboxnpcs_helitrack_road2_18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_18", Origin = "10240 10752 -9024", Target = "esboxnpcs_helitrack_road2_19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_19", Origin = "9792 12800 -8704", Target = "esboxnpcs_helitrack_road2_20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_20", Origin = "9920 13824 -8704", Target = "esboxnpcs_helitrack_road2_21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road2_21", Origin = "10240 14528 -8704", Target = "", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Railroad 1
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_1", Origin = "-14496 3296 -9408", Target = "esboxnpcs_helitrack_railroad1_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_2", Origin = "-11776 3296 -9408", Target = "esboxnpcs_helitrack_railroad1_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_3", Origin = "-10752 3200 -9408", Target = "esboxnpcs_helitrack_railroad1_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_4", Origin = "-9728 3200 -9408", Target = "esboxnpcs_helitrack_railroad1_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_5", Origin = "-8576 3200 -9408", Target = "esboxnpcs_helitrack_railroad1_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_6", Origin = "-7296 3200 -9408", Target = "esboxnpcs_helitrack_railroad1_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_railroad1_7", Origin = "-5120 3200 -9408", Target = "esboxnpcs_helitrack_road2_1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Radio Tower
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_radiotower1", Origin = "-512 -6656 -8448", Target = "esboxnpcs_helitrack_radiotower2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_radiotower2", Origin = "-1024 -5632 -8448", Target = "esboxnpcs_helitrack_radiotower3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_radiotower3", Origin = "-256 -5376 -8448", Target = "esboxnpcs_helitrack_radiotower4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_radiotower4", Origin = "1024 -5120 -8448", Target = "esboxnpcs_helitrack_radiotower5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_radiotower5", Origin = "768 -6656 -8448", Target = "esboxnpcs_helitrack_radiotower1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Silo
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_silo1", Origin = "3072 -9216 -7168", Target = "esboxnpcs_helitrack_silo2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_silo2", Origin = "2048 -10240 -7168", Target = "esboxnpcs_helitrack_silo3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_silo3", Origin = "3840 -11008 -7040", Target = "esboxnpcs_helitrack_silo4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_silo4", Origin = "4384 -9632 -7040", Target = "esboxnpcs_helitrack_silo1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Base
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base1", Origin = "9600 -1664 -7168", Target = "esboxnpcs_helitrack_base2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base2", Origin = "10624 -896 -7168", Target = "esboxnpcs_helitrack_base3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base3", Origin = "11520 -2144 -6656", Target = "esboxnpcs_helitrack_base4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base4", Origin = "10496 -2816 -6912", Target = "esboxnpcs_helitrack_base5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base5", Origin = "10208 -4096 -6912", Target = "esboxnpcs_helitrack_base6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base6", Origin = "8704 -4352 -7040", Target = "esboxnpcs_helitrack_base7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_base7", Origin = "8704 -2816 -7168", Target = "esboxnpcs_helitrack_base1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Castle
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle1", Origin = "12800 12288 -6656", Target = "esboxnpcs_helitrack_castle2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle2", Origin = "12032 13824 -6656", Target = "esboxnpcs_helitrack_castle3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle3", Origin = "13312 14336 -6400", Target = "esboxnpcs_helitrack_castle4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle4", Origin = "14592 13568 -6144", Target = "esboxnpcs_helitrack_castle5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle5", Origin = "14592 11520 -6144", Target = "esboxnpcs_helitrack_castle6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle6", Origin = "14080 10496 -6144", Target = "esboxnpcs_helitrack_castle7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_castle7", Origin = "13056 10496 -6400", Target = "esboxnpcs_helitrack_castle1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Church
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church1", Origin = "-6752 -12288 -8448", Target = "esboxnpcs_helitrack_church2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church2", Origin = "-6912 -13056 -8448", Target = "esboxnpcs_helitrack_church3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church3", Origin = "-7680 -13568 -8448", Target = "esboxnpcs_helitrack_church4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church4", Origin = "-8960 -13312 -8448", Target = "esboxnpcs_helitrack_church5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church5", Origin = "-9472 -12032 -8448", Target = "esboxnpcs_helitrack_church6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_church6", Origin = "-8320 -11552 -8448", Target = "esboxnpcs_helitrack_church1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Road 3
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_1", Origin = "-3072 -5376 -8640", Target = "esboxnpcs_helitrack_road3_2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_2", Origin = "-1248 -7200 -8640", Target = "esboxnpcs_helitrack_road3_3", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_3", Origin = "-224 -8064 -8640", Target = "esboxnpcs_helitrack_road3_4", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_4", Origin = "768 -8256 -8640", Target = "esboxnpcs_helitrack_road3_5", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_5", Origin = "3072 -8320 -8448", Target = "esboxnpcs_helitrack_road3_6", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_6", Origin = "4096 -8320 -8192", Target = "esboxnpcs_helitrack_road3_7", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_7", Origin = "5120 -8320 -8448", Target = "esboxnpcs_helitrack_road3_8", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_8", Origin = "5632 -7424 -8448", Target = "esboxnpcs_helitrack_road3_9", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_9", Origin = "5888 -5440 -8320", Target = "esboxnpcs_helitrack_road3_10", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_10", Origin = "7680 -3584 -8192", Target = "esboxnpcs_helitrack_road3_11", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_11", Origin = "7520 -2464 -8064", Target = "esboxnpcs_helitrack_road3_12", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_12", Origin = "6976 -1184 -7456", Target = "esboxnpcs_helitrack_road3_13", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_13", Origin = "7456 -192 -8064", Target = "esboxnpcs_helitrack_road3_14", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_14", Origin = "8448 256 -7936", Target = "esboxnpcs_helitrack_road3_15", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_15", Origin = "9472 0 -7808", Target = "esboxnpcs_helitrack_road3_16", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_16", Origin = "9824 -768 -7808", Target = "esboxnpcs_helitrack_road3_17", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_17", Origin = "9472 -1408 -7680", Target = "esboxnpcs_helitrack_road3_18", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_18", Origin = "8800 -1440 -7680", Target = "esboxnpcs_helitrack_road3_19", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_19", Origin = "7776 -1216 -7584", Target = "esboxnpcs_helitrack_road3_20", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_20", Origin = "6976 -1184 -7552", Target = "esboxnpcs_helitrack_road3_21", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_21", Origin = "5888 -1184 -7520", Target = "esboxnpcs_helitrack_road3_22", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_22", Origin = "4352 -1088 -7488", Target = "esboxnpcs_helitrack_road3_23", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_23", Origin = "3744 -256 -7456", Target = "esboxnpcs_helitrack_road3_24", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_24", Origin = "3968 1024 -7360", Target = "esboxnpcs_helitrack_road3_25", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_25", Origin = "5376 2560 -7168", Target = "esboxnpcs_helitrack_road3_26", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_26", Origin = "6208 2912 -7168", Target = "esboxnpcs_helitrack_road3_27", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_27", Origin = "6656 3584 -7168", Target = "esboxnpcs_helitrack_road3_28", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_28", Origin = "8448 4352 -7168", Target = "esboxnpcs_helitrack_road3_29", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_29", Origin = "9216 4224 -7040", Target = "esboxnpcs_helitrack_road3_30", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_30", Origin = "10880 4224 -7040", Target = "esboxnpcs_helitrack_road3_31", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_31", Origin = "12544 6016 -7040", Target = "esboxnpcs_helitrack_road3_32", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_32", Origin = "12992 7488 -7040", Target = "esboxnpcs_helitrack_road3_33", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_road3_33", Origin = "14784 7776 -7040", Target = "", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	-- Runway
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_runway1", Origin = "11584 -10272 -5632", Target = "esboxnpcs_helitrack_runway2", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	{ Class = "path_track", Targetname = "esboxnpcs_helitrack_runway2", Origin = "6656 -12800 -5632", Target = "esboxnpcs_helitrack_runway1", OrientationType = 0, OnPass = "esboxnpcs_helitrack_autofly,RunCode,0,-1" },
	
	{ Class = "lua_run", Targetname = "esboxnpcs_helitrack_autofly", Origin = "0 0 1024", Code = "ESBOXNPCS_InternalPathHandler(ACTIVATOR, CALLER)" },
}

