list.Add( "NPCUsableWeapons", { class = "npc_m9k_coltpython",	title = "M9K_Coltpython" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m29satan",	title = "M9K_m29satan" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_model3russian",	title = "M9K_model3russian" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_model500",	title = "M9K_model500" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_model627",	title = "M9K_model627" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ragingbull",	title = "M9K_ragingbull" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_remington1858",	title = "M9K_remington1858" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_scoped_taurus",	title = "M9K_scopedtaurus" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_colt1911",	title = "M9K_colt1911" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_deagle",	title = "M9K_deagle" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_hk45",	title = "M9K_hk45" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_luger",	title = "M9K_luger" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m92beretta",	title = "M9K_m92beretta" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_sig_p229r",	title = "M9K_sigp229r" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_usp",	title = "M9K_usp" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_glock18",	title = "M9K_glock18" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_bizonp19",	title = "M9K_bizon" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_honeybadger",	title = "M9K_honeybadger" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_kac_pdw",	title = "M9K_kacpdw" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_magpulpdr",	title = "M9K_magpulpdr" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mp5",	title = "M9K_mp5" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mp5sd",	title = "M9K_mp5sd" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mp7",	title = "M9K_mp7" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mp9",	title = "M9K_mp9" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mp40",	title = "M9K_mp40" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_smgp90",	title = "M9K_p90" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_sten",	title = "M9K_sten" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_tec9",	title = "M9K_tec9" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_thompson",	title = "M9K_thompson" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ump45",	title = "M9K_ump45" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_usc",	title = "M9K_usc" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_uzi",	title = "M9K_uzi" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_vector",	title = "M9K_vector" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_1887winchester",	title = "M9K_1887winchester" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_1897winchester",	title = "M9K_1897winchester" }  ) 
list.Add( "NPCUsableWeapons", { class = "npc_m9k_browningauto5",	title = "M9K_browningauto5" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_dbarrel",	title = "M9K_doublebarreledshotgun" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_jackhammer",	title = "M9K_jackhammer" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m3",	title = "M9K_m3" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ithacam37",	title = "M9K_ithacam37" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_mossberg590",	title = "M9K_mossberg590" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_remington870",	title = "M9K_remington870" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_spas12",	title = "M9K_spas12" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_striker12",	title = "M9K_striker12" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_usas",	title = "M9K_usas" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ares_shrike",	title = "M9K_aresshrike" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_fg42",	title = "M9K_fg42" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m60",	title = "M9K_m60" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m249lmg",	title = "M9K_m249lmg" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m1918bar",	title = "M9K_m1918bar" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_minigun",	title = "M9K_minigun" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_pkm",	title = "M9K_pkm" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_aw50",	title = "M9K_aw50" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_barret_m82",	title = "M9K_barretm82" }  ) 
list.Add( "NPCUsableWeapons", { class = "npc_m9k_contender",	title = "M9K_contender" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_dragunov",	title = "M9K_dragunov" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_intervention",	title = "M9K_intervention" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m24",	title = "M9K_m24" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m98b",	title = "M9K_m98b" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_psg1",	title = "M9K_psg1" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_remington7615p",	title = "M9K_remington7615p" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_sl8",	title = "M9K_sl8" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_svt40",	title = "M9K_svt40" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_svu",	title = "M9K_svu" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_acr",	title = "M9K_ACR" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ak47",	title = "M9K_AK47" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_ak74",	title = "M9K_AK74" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_amd65",	title = "M9K_Amd65" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_an94",	title = "M9K_An94" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_auga3",	title = "M9K_Aug" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_f2000",	title = "M9K_F2000" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_fal",	title = "M9K_fal" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_famas",	title = "M9K_famas" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_g3a3",	title = "M9K_g3a3" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_g36",	title = "M9K_g36" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_l85",	title = "M9K_l85" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m4a1",	title = "M9K_m4a1" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m14sp",	title = "M9K_m14" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m16a4_acog",	title = "M9K_M16Acog" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_m416",	title = "M9K_M4" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_scar",	title = "M9K_scar" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_tar21",	title = "M9K_tar21" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_val",	title = "M9K_val" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_vikhr",	title = "M9K_vikhr" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_winchester73",	title = "M9K_winchester73" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_rpg7",	title = "M9K_rpg7" }  )
list.Add( "NPCUsableWeapons", { class = "npc_m9k_matador",	title = "M9K_matador" }  )


sound.Add({
	name =				"RPGF.single",
	channel =			CHAN_USER_BASE+10,
	volume =			1.0,
	soundlevel =			155,
	sound =				"GDC/Rockets/RPGF.wav"
})

sound.Add({
	name =				"MATADORF.single",
	channel =			CHAN_USER_BASE+10,
	volume =			1.0,
	soundlevel =			155,
	sound =				"GDC/Rockets/MATADORF.wav"
})