-- This SWEP was generated by mblunk's swep factory.
SWEP.Base = "weapon_base"

-- Visual/sound settings
if ( SERVER ) then
	AddCSLuaFile( "shared.lua" )
	SWEP.HoldType			= "ar2"
end

SWEP.PrintName		= "Pulse Sniper Rifle"
SWEP.Category 			= "NPC Combine SWEPs"
SWEP.Slot		    = 4
SWEP.SlotPos		= 4
SWEP.DrawAmmo		= true
SWEP.DrawCrosshair		= true
SWEP.FiresUnderwater = false
SWEP.UseHands			= true
SWEP.ViewModelFOV			= 45
SWEP.ViewModel		= "models/v_models/v_crossbow.mdl"
SWEP.WorldModel		= "models/weapons/w_combinesniper_e2.mdl"
SWEP.ReloadSound		= "npc/sniper/reload1.wav"
SWEP.MuzzleAttachment	= "1"

-- Other settings
SWEP.Weight		= 5
SWEP.Spawnable		= false
SWEP.AdminSpawnable	= false
 
-- SWEP info
SWEP.Author		= "Zach88889"
SWEP.Contact		= "Nothing.com.org.net.You're dumb for looking at this."
SWEP.Purpose		= "Just your normal futuristic sniper rifle."
SWEP.Instructions	= "Use it like every other weapon in the Game."

-- Primary fire settings
SWEP.FireDelay = 0
SWEP.Primary.Sound			= "SniperFire.Play"
SWEP.Primary.NumShots		= 1
SWEP.Primary.Delay			= 2.15
SWEP.Primary.ClipSize		= 1	
SWEP.Primary.DefaultClip	= 1	
SWEP.Primary.Tracer			= 1
SWEP.Primary.Automatic		= false
SWEP.Primary.TakeAmmoPerBullet	= false
SWEP.Primary.Ammo		= "ar2"
//SWEP.Primary.Ammo		= "SniperRound"
SWEP.Primary.DistantSound 		= "SniperEcho.Play"
SWEP.Primary.DistantSoundLevel= 140
SWEP.Primary.DistantSoundPitch1= 80
SWEP.Primary.DistantSoundPitch2= 75
SWEP.Primary.DistantSoundVolume= 0.4

-- Hooks
function SWEP:Equip(owner)
	self:SetWeaponHoldType( self.HoldType )
	timer.Simple(0.01, function()
	if IsValid(self) && IsValid(owner) then
		if owner:GetClass() == "npc_combine_s" || owner:GetClass() == "npc_citizen" then
			owner:SetCurrentWeaponProficiency( WEAPON_PROFICIENCY_PERFECT )
		end
		owner:CapabilitiesRemove(64)
	end
	end)
end

function SWEP:PrimaryAttack()
if IsValid(self.Owner:GetEnemy()) then
	self.Weapon:SendWeaponAnim( ACT_VM_PRIMARYATTACK )
	self.FireDelay = CurTime() + self.Primary.Delay
	self:SetNextPrimaryFire( self.FireDelay )
	sound.Play(Sound(self.Primary.DistantSound),self:GetPos(),self.Primary.DistantSoundLevel,math.random(self.Primary.DistantSoundPitch1,self.Primary.DistantSoundPitch2),self.Primary.DistantSoundVolume)
	self:ShotThatThing()
	end
end

function SWEP:ShotThatThing()
	local attPos = self.Owner:GetShootPos()
	local attAng = self:GetAttachment(self.MuzzleAttachment).Ang
	local posTgt = self.Owner:GetEnemy():BodyTarget(attPos)
	local angAcc = (posTgt-attPos):Angle()
	local bullet = {}
		bullet.Num = self.Primary.NumberofShots //The number of shots fired
		bullet.Src = self.Owner:GetShootPos() //Gets where the bullet comes from
		bullet.Dir = Angle(math.ApproachAngle(attAng.p,angAcc.p,45),math.ApproachAngle(attAng.y,angAcc.y,35),0):Forward()
		bullet.Tracer = 1
		bullet.Spread = Vector(0.005,0.005,0.005)*(5-self.Owner:GetCurrentWeaponProficiency())
		bullet.Damage = GetConVarNumber("sk_npc_dmg_sniper_round")
		bullet.AmmoType = self.Primary.Ammo
		bullet.TracerName = "AR2Tracer"
	self.Owner:FireBullets( bullet )
	self.Owner:MuzzleFlash()
	self.Weapon:EmitSound(Sound(self.Primary.Sound))
	self:TakePrimaryAmmo( 1 )
end

function SWEP:SecondaryAttack()
end

function SWEP:Think()
if !IsValid(self) or !IsValid(self.Owner) then return end

if self.Owner:IsCurrentSchedule(43) then
	self:NPCShoot_Primary( ShootPos, ShootDir )
	end

if self.Owner:IsCurrentSchedule(51) then
	self:Reload()
	end
end

function SWEP:NPCShoot_Primary( ShootPos, ShootDir )
if !IsValid(self) or !IsValid(self.Owner) or self:Clip1() <= 0 or self.FireDelay > CurTime() then return end
	self:PrimaryAttack()
end

function SWEP:Reload()
if !IsValid(self) or !IsValid(self.Owner) then return end
	self.Weapon:EmitSound(self.ReloadSound)
	self:SetClip1(self.Primary.ClipSize)
end

function SWEP:Deploy()				
	return true
end

function SWEP:Holster()				
	return true
end

function SWEP:OnRemove()			
end

function SWEP:OnRestore()			
end

function SWEP:Precache()			
end

function SWEP:OwnerChanged()		
end

function SWEP:OnDrop()
	self:SetKeyValue("spawnflags", tostring(bit.bor(tonumber(self:GetKeyValues()["spawnflags"]), 2)))
end

sound.Add( {
	name = "SniperFire.Play",
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 90,
	pitch = { 100, 100 },
	sound = "npc/sniper/echo1.wav"
} )

sound.Add( {
	name = "SniperEcho.Play",
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 90,
	pitch = { 100, 100 },
	sound = "npc/sniper/sniper1.wav"
} )